name: Release application

on:
  push:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  FRONTEND_IMAGE: frontend
  BACKEND_IMAGE: backend
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - run: gcloud --quiet auth configure-docker
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Create image name and tag
      run: |-
        echo "::set-env name=FRONTEND_IMAGE_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/$FRONTEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
        echo "::set-env name=BACKEND_IMAGE_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/$BACKEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
    - name: Build
      run: |-
        docker build --tag "$FRONTEND_IMAGE_WITH_TAG" frontend
        docker build --tag "$BACKEND_IMAGE_WITH_TAG" backend
    - name: Publish
      run: |-
        docker push "$FRONTEND_IMAGE_WITH_TAG"
        docker push "$BACKEND_IMAGE_WITH_TAG"
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    - name: Deploy
      run: |-
        ./kustomize edit set image FRONTEND/IMAGE=$FRONTEND_IMAGE_WITH_TAG BACKEND/IMAGE=$BACKEND_IMAGE_WITH_TAG
        kubectl apply -k .
        kubectl rollout status deployment $IMAGE